/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ObservatoryRouteImport } from './routes/observatory'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionsIdRouteImport } from './routes/missions_.$id'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatoryRoute = ObservatoryRouteImport.update({
  id: '/observatory',
  path: '/observatory',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIdRoute = MissionsIdRouteImport.update({
  id: '/missions_/$id',
  path: '/missions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/communications': typeof CommunicationsRoute
  '/constitution': typeof ConstitutionRoute
  '/finance': typeof FinanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/missions': typeof MissionsRoute
  '/observatory': typeof ObservatoryRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/missions/$id': typeof MissionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/communications': typeof CommunicationsRoute
  '/constitution': typeof ConstitutionRoute
  '/finance': typeof FinanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/missions': typeof MissionsRoute
  '/observatory': typeof ObservatoryRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/missions/$id': typeof MissionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/communications': typeof CommunicationsRoute
  '/constitution': typeof ConstitutionRoute
  '/finance': typeof FinanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/missions': typeof MissionsRoute
  '/observatory': typeof ObservatoryRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/missions_/$id': typeof MissionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/communications'
    | '/constitution'
    | '/finance'
    | '/knowledge'
    | '/missions'
    | '/observatory'
    | '/settings'
    | '/timeline'
    | '/missions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/communications'
    | '/constitution'
    | '/finance'
    | '/knowledge'
    | '/missions'
    | '/observatory'
    | '/settings'
    | '/timeline'
    | '/missions/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/communications'
    | '/constitution'
    | '/finance'
    | '/knowledge'
    | '/missions'
    | '/observatory'
    | '/settings'
    | '/timeline'
    | '/missions_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CommunicationsRoute: typeof CommunicationsRoute
  ConstitutionRoute: typeof ConstitutionRoute
  FinanceRoute: typeof FinanceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  MissionsRoute: typeof MissionsRoute
  ObservatoryRoute: typeof ObservatoryRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  MissionsIdRoute: typeof MissionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatory': {
      id: '/observatory'
      path: '/observatory'
      fullPath: '/observatory'
      preLoaderRoute: typeof ObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions_/$id': {
      id: '/missions_/$id'
      path: '/missions/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof MissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CommunicationsRoute: CommunicationsRoute,
  ConstitutionRoute: ConstitutionRoute,
  FinanceRoute: FinanceRoute,
  KnowledgeRoute: KnowledgeRoute,
  MissionsRoute: MissionsRoute,
  ObservatoryRoute: ObservatoryRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  MissionsIdRoute: MissionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
