/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionsIdRouteImport } from './routes/missions.$id'

const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIdRoute = MissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/missions': typeof MissionsRouteWithChildren
  '/missions/$id': typeof MissionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/missions': typeof MissionsRouteWithChildren
  '/missions/$id': typeof MissionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/missions': typeof MissionsRouteWithChildren
  '/missions/$id': typeof MissionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/missions' | '/missions/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/missions' | '/missions/$id'
  id: '__root__' | '/' | '/missions' | '/missions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissionsRoute: typeof MissionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$id': {
      id: '/missions/$id'
      path: '/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof MissionsIdRouteImport
      parentRoute: typeof MissionsRoute
    }
  }
}

interface MissionsRouteChildren {
  MissionsIdRoute: typeof MissionsIdRoute
}

const MissionsRouteChildren: MissionsRouteChildren = {
  MissionsIdRoute: MissionsIdRoute,
}

const MissionsRouteWithChildren = MissionsRoute._addFileChildren(
  MissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissionsRoute: MissionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
